spring:
  shardingsphere:
    enabled: false
  datasource:
    dynamic:
      primary: tradeDataSource
      strict: true
      datasource:
        druid:
          initialSize: 3
          minIdle: 3
          maxActive: 20
        tradeDataSource:
          url: jdbc:h2:mem:member_db;DB_CLOSE_DELAY=-1;mode=MySQL;
          ## #TRACE_LEVEL_SYSTEM_OUT=2;
          username: sa
          password: dean
          driverClassName: org.h2.Driver
          schema: classpath:sql/member_db.sql
        skuDataSource:
          url: jdbc:h2:mem:member_sku;DB_CLOSE_DELAY=-1;mode=MySQL;
          ## #TRACE_LEVEL_SYSTEM_OUT=2;
          username: sa
          password: dean
          driverClassName: org.h2.Driver
          schema: classpath:sql/member_sku.sql
          data: classpath:sql/init_demo_sku_ut.sql
  h2:
    console:
      enabled: true

eureka:
  client:
    enable: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 禁用向 eureka 注册
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false


logging:
  config: classpath:log/log4j2-ut.xml

## 单元测试模式下尽可能不依赖外部中间件,因此均使用本地模式.
memberclub:
  infrastructure:
    config: local
    lock: local
    feign:
      enabled: false
    id: local
    retry: local
    mq: local
    order: local
    asset: local
    sku: local
    cache: local
    usertag: local
  extension:
    bootcheck: true


apollo:
  meta: http://localhost:8080
  bootstrap:
    enabled: true

### 业务自定义配置项 Start
junit_test_poll_config: false

once_task_scan_period_perform_pre_days_1: 70
once_task_scan_aftersale_expire_refund_pre_days_2: 16
renewable_1: 2
### 业务自定义配置项 END
